version: '3'
tasks:
  test:
    desc: Run tests
    cmds:
      - go test -v ./...
  coverage:
    desc: Run tests with coverage
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -func=coverage.out
  nats:
    desc: Run nats server
    cmds:
      - nats-server